- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: æœªåˆ†ç±»'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: æœªåˆ†ç±»'
- en: 'date: 2024-05-18 05:42:28'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-18 05:42:28'
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Application Performance Metrics | Tales from a Trading Desk
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: åº”ç”¨ç¨‹åºæ€§èƒ½æŒ‡æ ‡ | äº¤æ˜“å°çš„ä¼ è¯´
- en: æ¥æºï¼š[https://mdavey.wordpress.com/2015/05/11/application-performance-metrics/#0001-01-01](https://mdavey.wordpress.com/2015/05/11/application-performance-metrics/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: æ¥æºï¼š[https://mdavey.wordpress.com/2015/05/11/application-performance-metrics/#0001-01-01](https://mdavey.wordpress.com/2015/05/11/application-performance-metrics/#0001-01-01)
- en: Application Performance Metrics
  id: totrans-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: åº”ç”¨ç¨‹åºæ€§èƒ½æŒ‡æ ‡
- en: InfoQ has an interesting [article](http://java.dzone.com/articles/top-5-java-performance-metrics)
    on â€œTop 5 Java Performance Metrics to Capture in Enterprise Applicationsâ€.Â  Performance
    has, and continues to be in many scenarios, the last to the software engineering
    party.Â  Once a team has got over the library sweet shop mentality, hopefully validate
    their proposed architecture, and ideally gone down an executable [specification](http://agilemodeling.com/essays/executableSpecifications.htm)
    road, the team often has either completely forgotten about performance, or decided
    to build a performance framework that has not correlation to theÂ executable specification
    road used from a feature perspective.Â  You can see the gaping hole ğŸ™‚
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: InfoQ åœ¨â€œ[ä¼ä¸šåº”ç”¨ç¨‹åºä¸­å¿…é¡»æ•è·çš„å‰ 5 ä¸ª Java æ€§èƒ½æŒ‡æ ‡](http://java.dzone.com/articles/top-5-java-performance-metrics)â€ä¸Šæœ‰ä¸€ç¯‡æœ‰è¶£çš„æ–‡ç« ã€‚åœ¨è®¸å¤šæƒ…å†µä¸‹ï¼Œæ€§èƒ½ä¸€ç›´æ˜¯è½¯ä»¶å·¥ç¨‹çš„æœ€åä¸€ä¸ªè€ƒè™‘å› ç´ ã€‚ä¸€æ—¦å›¢é˜Ÿæ‘†è„±äº†å›¾ä¹¦é¦†ç”œå“åº—çš„å¿ƒæ€ï¼Œå¸Œæœ›éªŒè¯ä»–ä»¬æå‡ºçš„æ¶æ„ï¼Œå¹¶ç†æƒ³æƒ…å†µä¸‹èµ°ä¸Šå¯æ‰§è¡Œ[è§„èŒƒ](http://agilemodeling.com/essays/executableSpecifications.htm)ä¹‹è·¯ï¼Œå›¢é˜Ÿå¾€å¾€è¦ä¹ˆå®Œå…¨å¿˜è®°äº†æ€§èƒ½ï¼Œè¦ä¹ˆå†³å®šæ„å»ºä¸€ä¸ªä¸ä»ç‰¹æ€§è§’åº¦ä½¿ç”¨çš„å¯æ‰§è¡Œè§„èŒƒè·¯çº¿æ²¡æœ‰å…³è”çš„æ€§èƒ½æ¡†æ¶ã€‚ä½ å¯ä»¥çœ‹åˆ°å­˜åœ¨çš„å·¨å¤§æ¼æ´
    ğŸ™‚
- en: 'Business Transactions provide insight into real-user behavior: they capture
    real-time performance that real users are experiencing as they interact with your
    application. As mentioned in the previous article, measuring the performance of
    a business transaction involves capturing the response time of a business transaction
    holistically as well as measuring the response times of its constituent tiers.
    These response times can then be compared with the baseline that best meets your
    business needs to determine normalcy.'
  id: totrans-8
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: ä¸šåŠ¡äº¤æ˜“æä¾›å¯¹çœŸå®ç”¨æˆ·è¡Œä¸ºçš„æ´å¯Ÿï¼šå®ƒä»¬æ•è·äº†ç”¨æˆ·ä¸æ‚¨çš„åº”ç”¨ç¨‹åºäº¤äº’æ—¶æ­£åœ¨ä½“éªŒçš„å®æ—¶æ€§èƒ½ã€‚å¦‚å‰æ–‡æ‰€è¿°ï¼Œè¡¡é‡ä¸šåŠ¡äº¤æ˜“çš„æ€§èƒ½æ¶‰åŠå…¨é¢æ•è·ä¸šåŠ¡äº¤æ˜“çš„å“åº”æ—¶é—´ï¼Œä»¥åŠæµ‹é‡å…¶ç»„æˆéƒ¨åˆ†å±‚çš„å“åº”æ—¶é—´ã€‚ç„¶åï¼Œå¯ä»¥å°†è¿™äº›å“åº”æ—¶é—´ä¸æœ€ç¬¦åˆæ‚¨ä¸šåŠ¡éœ€æ±‚çš„åŸºå‡†è¿›è¡Œæ¯”è¾ƒï¼Œä»¥ç¡®å®šæ­£å¸¸æ€§ã€‚
- en: Basic stuff.Â  Time to review if you are not doing this already
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: åŸºç¡€çŸ¥è¯†ã€‚å¦‚æœä½ è¿˜æ²¡æœ‰åšè¿™ä¸ªï¼Œç°åœ¨æ˜¯æ—¶å€™å®¡æŸ¥ä¸€ä¸‹äº†
- en: ~ by mdavey on May 11, 2015.
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: ~ ä½œè€… mdaveyï¼Œäº 2015 å¹´ 5 æœˆ 11 æ—¥å‘å¸ƒã€‚
- en: Posted in [Agile](https://mdavey.wordpress.com/category/agile/)
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: å‘å¸ƒåœ¨[æ•æ·](https://mdavey.wordpress.com/category/agile/)åˆ†ç±»ä¸‹
