- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: æœªåˆ†ç±»'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: ç±»åˆ«ï¼šæœªåˆ†ç±»
- en: 'date: 2024-05-18 05:32:54'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: æ—¥æœŸï¼š2024å¹´5æœˆ18æ—¥ 05:32:54
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Culture Impacts Application Performance | Tales from a Trading Desk
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: æ–‡åŒ–å½±å“åº”ç”¨æ€§èƒ½ | ä¸€ä¸ªäº¤æ˜“æ¡Œçš„æ•…äº‹
- en: æ¥æºï¼š[https://mdavey.wordpress.com/2016/04/30/culture-impacts-application-performance/#0001-01-01](https://mdavey.wordpress.com/2016/04/30/culture-impacts-application-performance/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: æ¥æºï¼š[https://mdavey.wordpress.com/2016/04/30/culture-impacts-application-performance/#0001-01-01](https://mdavey.wordpress.com/2016/04/30/culture-impacts-application-performance/#0001-01-01)
- en: 'Yet another classic [article](http://joeduffyblog.com/2016/04/10/performance-culture/)
    from Joe Duffy, this time on Performance Culture. Joe sums the whole performance
    culture issue up quite well in the early part of his essay:'
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: å¦ä¸€ç¯‡ç»å…¸çš„[æ–‡ç« ](http://joeduffyblog.com/2016/04/10/performance-culture/)æ¥è‡ªJoe Duffyï¼Œè¿™æ¬¡æ˜¯å…³äºæ€§èƒ½æ–‡åŒ–ã€‚ä¹”åœ¨ä»–çš„æ–‡ç« æ—©æœŸå¾ˆå¥½åœ°æ¦‚æ‹¬äº†æ•´ä¸ªæ€§èƒ½æ–‡åŒ–é—®é¢˜ï¼š
- en: The cultural transformation must start from the top â€“ management taking an active
    role in performance, asking questions, seeking insights, demanding rigor â€“ while
    it simultaneously comes from the bottom â€“ engineers actively seeking to understand
    performance of the code they are writing, ruthlessly taking a zero-tolerance stance
    on regressions, and being ever-self-critical and on the lookout for proactive
    improvements.
  id: totrans-7
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: æ–‡åŒ–è½¬å˜å¿…é¡»ä»é«˜å±‚å¼€å§‹ - ç®¡ç†å±‚ç§¯æå‚ä¸æ€§èƒ½ï¼Œæå‡ºé—®é¢˜ï¼Œå¯»æ±‚è§è§£ï¼Œè¦æ±‚ä¸¥æ ¼æ€§ï¼Œä¸æ­¤åŒæ—¶ä¹Ÿå¿…é¡»æ¥è‡ªä¸‹å±‚ - å·¥ç¨‹å¸ˆç§¯æå¯»æ±‚ç†è§£ä»–ä»¬æ­£åœ¨ç¼–å†™çš„ä»£ç çš„æ€§èƒ½ï¼Œå¯¹é€€åŒ–é—®é¢˜æ¯«ä¸ç•™æƒ…ï¼Œä¸æ–­è‡ªæˆ‘æ‰¹è¯„ï¼Œå¹¶ä¸”ç§¯æå¯»æ±‚ç§¯æçš„æ”¹è¿›ã€‚
- en: For me, the major issue that performance issues stem from in engineering is
    management. The drive on features, ignoring performance, and likewise not understanding
    the engineering demands required from engineering to achieve performance, come
    back to Joeâ€™s classic comment, â€œManagement must care â€œ. In many cases, I truly
    donâ€™t think management care, or care to understand.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: å¯¹æˆ‘æ¥è¯´ï¼Œå·¥ç¨‹ä¸­æ€§èƒ½é—®é¢˜çš„ä¸»è¦é—®é¢˜æ˜¯ç®¡ç†ã€‚è¿½æ±‚åŠŸèƒ½ï¼Œå¿½è§†æ€§èƒ½ï¼Œä»¥åŠåŒæ ·åœ°ä¸äº†è§£å·¥ç¨‹éœ€æ±‚æ‰€è¦æ±‚çš„æ€§èƒ½ï¼Œéƒ½å½’ç»“ä¸ºä¹”çš„ç»å…¸è¯„è®ºï¼Œâ€œç®¡ç†å¿…é¡»åœ¨æ„â€ã€‚åœ¨å¾ˆå¤šæƒ…å†µä¸‹ï¼Œæˆ‘çœŸçš„ä¸è®¤ä¸ºç®¡ç†å±‚åœ¨æ„ï¼Œæˆ–è€…æ„¿æ„ç†è§£ã€‚
- en: Its impossible not to disagree with the single appointed test/performance team
    member. This is the same outside of performance in the general quality space,
    and the â€œtesterâ€ silo mentality ğŸ˜¦
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: åœ¨å•ä¸€ä»»å‘½çš„æµ‹è¯•/æ€§èƒ½å›¢é˜Ÿæˆå‘˜é¢å‰ï¼Œä¸å¯èƒ½ä¸å‘ç”Ÿåˆ†æ­§ã€‚è¿™ä¸ä¸€èˆ¬è´¨é‡ç©ºé—´å†…çš„è¡¨ç°ä¸€æ ·ï¼Œä»¥åŠâ€œæµ‹è¯•å‘˜â€ç‹¬ç«‹å¿ƒæ€ ğŸ˜¦
- en: engineers learned bad habits by outsourcing the basic quality of their code,
    assuming that someone else would catch any problems that arise.
  id: totrans-10
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: å·¥ç¨‹å¸ˆé€šè¿‡å¤–åŒ…ä»–ä»¬çš„ä»£ç çš„åŸºæœ¬è´¨é‡ï¼Œè€Œå‡è®¾ä¼šæœ‰å…¶ä»–äººå‘ç°å‡ºç°çš„ä»»ä½•é—®é¢˜ï¼Œå­¦ä¼šäº†åä¹ æƒ¯ã€‚
- en: â€œMy number one rule is â€˜no jerks,'â€ â€“ hard not to disagree with this. Shame
    when jerks are forced on teams by management ğŸ˜¦
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: â€œæˆ‘çš„ç¬¬ä¸€æ¡è§„åˆ™æ˜¯â€˜ä¸è¦å’Œæ··è›‹ä¸€èµ·å·¥ä½œâ€™â€ï¼Œè¿™æ˜¯å¾ˆéš¾ä¸åŒæ„çš„ã€‚å½“æ··è›‹è¢«ç®¡ç†å±‚å¼ºè¿«åŠ å…¥å›¢é˜Ÿæ—¶ï¼ŒçœŸæ˜¯ä¸€ç§è€»è¾± ğŸ˜¦
- en: In every team with a poor performance culture, itâ€™s managementâ€™s fault. Period.
    End of conversation.
  id: totrans-12
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: åœ¨ä»»ä½•ä¸€ä¸ªæ€§èƒ½æ–‡åŒ–è´«ä¹çš„å›¢é˜Ÿä¸­ï¼Œéƒ½æ˜¯ç®¡ç†çš„é”™ã€‚è¯å·²ç»è¯´åˆ°è¿™é‡Œï¼Œæ²¡æœ‰è®¨è®ºçš„ä½™åœ°äº†ã€‚
- en: 'Finding the balance between performance and features is critical, else the
    cost to resolve performance with be a multipe of the original non allocated time:'
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: åœ¨æ€§èƒ½å’ŒåŠŸèƒ½ä¹‹é—´æ‰¾åˆ°å¹³è¡¡è‡³å…³é‡è¦ï¼Œå¦åˆ™è§£å†³æ€§èƒ½æ‰€éœ€çš„æˆæœ¬å°†æ˜¯åŸå§‹éåˆ†é…æ—¶é—´çš„å€æ•°ï¼š
- en: Performance doesnâ€™t come for free. It costs the team by forcing them to slow
    down at times, to spend energy on things other than cranking out features
  id: totrans-14
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: æ€§èƒ½å¹¶éå…è´¹ã€‚å®ƒä¼šè®©å›¢é˜Ÿä¸å¾—ä¸åœ¨æŸäº›æ—¶å€™æ”¾æ…¢é€Ÿåº¦ï¼Œå»èŠ±è´¹ç²¾åŠ›å¤„ç†é™¤äº†æ¨å‡ºåŠŸèƒ½ä¹‹å¤–çš„äº‹æƒ…ã€‚
- en: Great to hear that Microsoft is following the path of â€œthe elimination of â€œtestâ€
    as a discipline mentioned â€ and a â€œrenewed focus on engineering systemsâ€.
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: å¾ˆé«˜å…´å¬åˆ°å¾®è½¯æ­£åœ¨èµ°â€œæ¶ˆé™¤â€œæµ‹è¯•â€ä½œä¸ºä¸€ç§å­¦ç§‘â€çš„é“è·¯ï¼Œä»¥åŠâ€œé‡æ–°å…³æ³¨å·¥ç¨‹ç³»ç»Ÿâ€ã€‚
- en: In my view, management in a lot of companies needs to wake up from the sleepy
    drug of features, features,features. Without a stable engineering backed culture
    within a team, driven by a sensible blend of features and engineering, products
    are doomed to fail, causing considerabel financial loss
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: åœ¨æˆ‘çœ‹æ¥ï¼Œè®¸å¤šå…¬å¸çš„ç®¡ç†å±‚éœ€è¦ä»åŠŸèƒ½ã€åŠŸèƒ½å’ŒåŠŸèƒ½çš„æ˜æ˜æ¬²ç¡ä¸­é†’æ¥ã€‚å¦‚æœä¸€ä¸ªå›¢é˜Ÿå†…éƒ¨æ²¡æœ‰ç¨³å›ºçš„å·¥ç¨‹æ”¯æŒæ–‡åŒ–ï¼Œç”±ä¸€ç§ç†æ€§çš„åŠŸèƒ½å’Œå·¥ç¨‹ç›¸ç»“åˆçš„ç†å¿µæ¨åŠ¨ï¼Œäº§å“æ³¨å®šä¼šå¤±è´¥ï¼Œé€ æˆç›¸å½“å¤§çš„è´¢åŠ¡æŸå¤±
- en: ~ by mdavey on April 30, 2016.
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: ~ ç”± mdavey äº2016å¹´4æœˆ30æ—¥å‘å¸ƒã€‚
- en: Posted in [Agile](https://mdavey.wordpress.com/category/agile/)
  id: totrans-18
  prefs: []
  type: TYPE_NORMAL
  zh: å‘è¡¨åœ¨[æ•æ·](https://mdavey.wordpress.com/category/agile/)
