- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: æœªåˆ†ç±»'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: åˆ†ç±»ï¼šæœªåˆ†ç±»
- en: 'date: 2024-05-18 05:41:54'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: æ—¥æœŸï¼š2024-05-18 05:41:54
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Low-latency Distributed Applications | Tales from a Trading Desk
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: ä½å»¶è¿Ÿåˆ†å¸ƒå¼åº”ç”¨ | äº¤æ˜“æ¡Œé¢æ•…äº‹
- en: æ¥æºï¼š[https://mdavey.wordpress.com/2015/06/09/low-latency-distributed-applications/#0001-01-01](https://mdavey.wordpress.com/2015/06/09/low-latency-distributed-applications/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: æ¥æºï¼š[https://mdavey.wordpress.com/2015/06/09/low-latency-distributed-applications/#0001-01-01](https://mdavey.wordpress.com/2015/06/09/low-latency-distributed-applications/#0001-01-01)
- en: Low-latency Distributed Applications
  id: totrans-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: ä½å»¶è¿Ÿåˆ†å¸ƒå¼åº”ç”¨
- en: 'Andrew Brookâ€™s [article](http://queue.acm.org/detail.cfm?id=2770868), â€œEvolution
    and Practice: Low-latency Distributed Applications in Financeâ€ offers a good read
    on low latency in finance. Â RFQâ€™s and RFS are appropriately covered coupled with
    the often overlooked â€œ[Clock](https://queue.acm.org/detail.cfm?id=2745385) synchronizationâ€
    ğŸ™‚ Â More thread than cores is also discussed â€“Â context switch.'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '[å®‰å¾·é²Â·å¸ƒé²å…‹](http://queue.acm.org/detail.cfm?id=2770868)çš„æ–‡ç« â€œæ¼”å˜ä¸å®è·µï¼šé‡‘èé¢†åŸŸçš„ä½å»¶è¿Ÿåˆ†å¸ƒå¼åº”ç”¨â€ä¸ºé‡‘èé¢†åŸŸçš„ä½å»¶è¿Ÿé—®é¢˜æä¾›äº†å¾ˆå¥½çš„é˜…è¯»ææ–™ã€‚RFQï¼ˆè¯·æ±‚æŠ¥ä»·ï¼‰å’ŒRFSï¼ˆè¯·æ±‚æœåŠ¡è§„æ ¼ï¼‰å¾—åˆ°äº†é€‚å½“çš„è¦†ç›–ï¼ŒåŒæ—¶è¿˜æåˆ°äº†ç»å¸¸è¢«å¿½è§†çš„â€œ[æ—¶é’ŸåŒæ­¥](http://queue.acm.org/detail.cfm?id=2745385)â€é—®é¢˜ã€‚æ­¤å¤–ï¼Œè¿˜è®¨è®ºäº†çº¿ç¨‹æ¯”æ ¸å¿ƒå¤šçš„æƒ…å†µä»¥åŠä¸Šä¸‹æ–‡åˆ‡æ¢çš„é—®é¢˜ã€‚'
- en: Hopefully these types of articles will aid in educating people on the decision
    made during the design of low latency architectures prior to them being implemented,
    and deployed into production, with sometimes unfortunate results.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: å¸Œæœ›è¿™ç±»æ–‡ç« èƒ½å¸®åŠ©äººä»¬åœ¨å®æ–½ä½å»¶è¿Ÿæ¶æ„ä¹‹å‰äº†è§£è®¾è®¡è¿‡ç¨‹ä¸­æ‰€åšçš„å†³ç­–ï¼Œä»¥åŠè¿™äº›å†³ç­–åœ¨ç”Ÿäº§ç¯å¢ƒä¸­éƒ¨ç½²æ—¶å¯èƒ½å¸¦æ¥çš„ä¸å¹¸ç»“æœã€‚
- en: 'Its also worth calling out [Aeronâ€™s](https://github.com/real-logic/Aeron) [Design](https://github.com/real-logic/Aeron/wiki/Design-Principles)
    Principles:'
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: è¿˜éœ€è¦ç‰¹åˆ«æŒ‡å‡º[Aeronçš„è®¾è®¡åŸåˆ™](https://github.com/real-logic/Aeron/wiki/Design-Principles)ï¼š
- en: To achieve low-latency with minimal variance, while achieving high throughput,
    it is important to define a set of design principles that guide the development.
    When a trade off is required then the design principles help guide the decision
    in choosing between competing alternatives.
  id: totrans-10
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: è¦åœ¨æœ€å°åŒ–æ–¹å·®çš„åŒæ—¶å®ç°ä½å»¶è¿Ÿå’Œé«˜ååé‡ï¼Œå®šä¹‰ä¸€å¥—æŒ‡å¯¼å¼€å‘çš„è®¾è®¡åŸåˆ™è‡³å…³é‡è¦ã€‚å½“éœ€è¦æƒè¡¡æ—¶ï¼Œè¿™äº›è®¾è®¡åŸåˆ™æœ‰åŠ©äºæŒ‡å¯¼å†³ç­–ï¼Œé€‰æ‹©ç›¸äº’ç«äº‰çš„æ›¿ä»£æ–¹æ¡ˆä¹‹é—´çš„æœ€ä½³æ–¹æ¡ˆã€‚
- en: There is no [free](http://www.infoq.com/presentations/java8-performance) lunch.
    Â Performance comes at a cost â€“ $ and/or time to develop.
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: æ²¡æœ‰å…è´¹çš„[åˆé¤](http://www.infoq.com/presentations/java8-performance)ã€‚æ€§èƒ½çš„æå‡éœ€è¦ä»˜å‡ºä»£ä»·â€”â€”è¦ä¹ˆæ˜¯é‡‘é’±ï¼Œè¦ä¹ˆæ˜¯å¼€å‘æ—¶é—´ã€‚
- en: ~ by mdavey on June 9, 2015.
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: ~ mdaveyäº2015å¹´6æœˆ9æ—¥ã€‚
- en: Posted in [Languages](https://mdavey.wordpress.com/category/languages/), [Trading](https://mdavey.wordpress.com/category/trading/)
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: å‘å¸ƒåœ¨[è¯­è¨€](https://mdavey.wordpress.com/category/languages/)ã€[äº¤æ˜“](https://mdavey.wordpress.com/category/trading/)åˆ†ç±»ä¸‹ã€‚
