- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: æœªåˆ†ç±»'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: åˆ†ç±»ï¼šæœªåˆ†ç±»
- en: 'date: 2024-05-18 05:59:35'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: æ—¥æœŸï¼š2024-05-18 05:59:35
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Reactor â€“ Asynchronous World of Application Building | Tales from a Trading
    Desk
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: Reactor â€“ åº”ç”¨æ„å»ºçš„å¼‚æ­¥ä¸–ç•Œ | äº¤æ˜“æ¡Œä¸Šçš„æ•…äº‹
- en: æ¥æºï¼š[https://mdavey.wordpress.com/2013/10/31/reactor-asynchronous-world-of-application-building/#0001-01-01](https://mdavey.wordpress.com/2013/10/31/reactor-asynchronous-world-of-application-building/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: æ¥æºï¼š[https://mdavey.wordpress.com/2013/10/31/reactor-asynchronous-world-of-application-building/#0001-01-01](https://mdavey.wordpress.com/2013/10/31/reactor-asynchronous-world-of-application-building/#0001-01-01)
- en: Reactor â€“ Asynchronous World of ApplicationÂ Building
  id: totrans-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: Reactor â€“ åº”ç”¨æ„å»ºçš„å¼‚æ­¥ä¸–ç•Œ
- en: Itâ€™s nice to see Reactor hitting the second M1 [milestone](http://spring.io/blog/2013/08/27/reactor-1-0-0-m2-a-foundation-for-reactive-fast-data-applications-on-the-jvm).Â 
    Having coded Rx on .NET, coupled with a lot of work recently with RxJava, it appears
    time to have a [detailed](http://jaxenter.com/springsource-s-asynchronous-jvm-framework-reactor-hits-first-milestone-47786.html)
    look at [Reactor](https://github.com/reactor/reactor).Â  Itâ€™s always nice to see
    a trading bias to the [samples](http://spring.io/blog/2013/07/18/reactor-1-0-0-m1-a-foundation-for-asynchronous-fast-data-applications-on-the-jvm/)
    of [reactive](http://www.youtube.com/watch?v=8jPJh1VFNpk&list=PLnCSV-Zt6sWWcKPoth3QeXhhcPcbJmrM8)
    frameworks ğŸ™‚
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: çœ‹åˆ°Reactorè¾¾åˆ°äº†ç¬¬äºŒä¸ªM1[é‡Œç¨‹ç¢‘](http://spring.io/blog/2013/08/27/reactor-1-0-0-m2-a-foundation-for-reactive-fast-data-applications-on-the-jvm)çœŸæ˜¯ä»¤äººé«˜å…´ã€‚åœ¨.NETä¸Šç¼–å†™äº†Rxä¹‹åï¼Œæœ€è¿‘åˆåšäº†å¤§é‡RxJavaçš„å·¥ä½œï¼Œä¼¼ä¹æ˜¯æ—¶å€™å¯¹[Reactor](https://github.com/reactor/reactor)è¿›è¡Œä¸€æ¬¡[è¯¦ç»†](http://jaxenter.com/springsource-s-asynchronous-jvm-framework-reactor-hits-first-milestone-47786.html)çš„äº†è§£äº†ã€‚çœ‹åˆ°[ç¤ºä¾‹](http://spring.io/blog/2013/07/18/reactor-1-0-0-m1-a-foundation-for-asynchronous-fast-data-applications-on-the-jvm)ä¸­æœ‰ä¸€ä¸ªäº¤æ˜“åè§
    towards [reactive](http://www.youtube.com/watch?v=8jPJh1VFNpk&list=PLnCSV-Zt6sWWcKPoth3QeXhhcPcbJmrM8)
    frameworksçœŸæ˜¯ä»¤äººæ„‰å¿«:)
- en: ~ by mdavey on October 31, 2013.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: ~ mdaveyäº2013å¹´10æœˆ31æ—¥ã€‚
- en: Posted in [Java](https://mdavey.wordpress.com/category/languages/java/)
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: å‘å¸ƒåœ¨[Java](https://mdavey.wordpress.com/category/languages/java/)
