- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: æœªåˆ†ç±»'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: åˆ†ç±»ï¼šæœªåˆ†ç±»
- en: 'date: 2024-05-18 05:34:15'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: æ—¥æœŸï¼š2024 å¹´ 5 æœˆ 18 æ—¥ 05:34:15
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Well-Architected Applications â€“ AWS Cloud and More | Tales from a Trading Desk
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: äº‘åŒ–åº”ç”¨æ¶æ„ - AWS äº‘å’Œæ›´å¤š | æ¥è‡ªäº¤æ˜“å°çš„æ•…äº‹
- en: æ¥æºï¼š[https://mdavey.wordpress.com/2016/04/13/well-architected-applications-aws-cloud-and-more/#0001-01-01](https://mdavey.wordpress.com/2016/04/13/well-architected-applications-aws-cloud-and-more/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: æ¥æºï¼š[https://mdavey.wordpress.com/2016/04/13/well-architected-applications-aws-cloud-and-more/#0001-01-01](https://mdavey.wordpress.com/2016/04/13/well-architected-applications-aws-cloud-and-more/#0001-01-01)
- en: Well-Architected Applications â€“ AWS Cloud andÂ More
  id: totrans-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: äº‘åŒ–åº”ç”¨æ¶æ„ - AWS äº‘å’Œæ›´å¤š
- en: Although â€œAWS [Well-Architected](https://d0.awsstatic.com/whitepapers/architecture/AWS_Well-Architected_Framework.pdf)
    Frameworkâ€ is clearly cloud focused, it has in my view a lot of relevant material
    for non-cloud applications. Â AWS Well-Architected Framework is based on four pillarsâ€”security,
    reliability, performance efficiency, and cost optimization. Â Clearly all four
    pillars are relevant to non-cloud applications, with cost optimization being high
    up due to budgets, hardware purchases, and data centre space.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: å°½ç®¡â€œAWS [Well-Architected](https://d0.awsstatic.com/whitepapers/architecture/AWS_Well-Architected_Framework.pdf)
    Frameworkâ€ æ˜ç¡®å…³æ³¨äº‘ï¼Œä½†æˆ‘è®¤ä¸ºå®ƒæœ‰å¾ˆå¤šç›¸å…³çš„éäº‘åº”ç”¨ææ–™ã€‚ AWS Well-Architected Framework åŸºäºå››ä¸ªæ”¯æŸ± - å®‰å…¨æ€§ã€å¯é æ€§ã€æ€§èƒ½æ•ˆç‡å’Œæˆæœ¬ä¼˜åŒ–ã€‚
    æ˜¾ç„¶ï¼Œè¿™å››ä¸ªæ”¯æŸ±å¯¹éäº‘åº”ç”¨ç¨‹åºä¹Ÿå¾ˆé‡è¦ï¼Œæˆæœ¬ä¼˜åŒ–æ˜¯ç”±äºé¢„ç®—ã€ç¡¬ä»¶é‡‡è´­å’Œæ•°æ®ä¸­å¿ƒç©ºé—´çš„é™åˆ¶ã€‚
- en: Cloud does have a number of benefits, one of which is â€œLower the risk of architecture
    changeâ€ â€“ something that all of us have probably experienced, testing in an environment
    which has a considerable delta to production. Â Cloud offers â€œautomate the creation
    of test environments that emulate your production configurations, you can carry
    out testing easily.â€
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: äº‘ç¡®å®æœ‰è®¸å¤šå¥½å¤„ï¼Œå…¶ä¸­ä¹‹ä¸€æ˜¯â€œé™ä½æ¶æ„å˜æ›´çš„é£é™©â€ - æˆ‘ä»¬æ‰€æœ‰äººå¯èƒ½éƒ½ç»å†è¿‡çš„äº‹æƒ…ä¹‹ä¸€æ˜¯ï¼Œåœ¨ä¸ç”Ÿäº§ç¯å¢ƒå­˜åœ¨ç›¸å½“å¤§å·®å¼‚çš„ç¯å¢ƒä¸­è¿›è¡Œæµ‹è¯•ã€‚ äº‘æä¾›â€œè‡ªåŠ¨åˆ›å»ºæ¨¡æ‹Ÿæ‚¨çš„ç”Ÿäº§é…ç½®çš„æµ‹è¯•ç¯å¢ƒï¼Œæ‚¨å¯ä»¥è½»æ¾è¿›è¡Œæµ‹è¯•ã€‚â€
- en: Similarly, data protection these days is often an important topic, especially
    in light of the EUâ€™sÂ General Data Protection [Regulation](http://www.computerweekly.com/news/450281144/European-Parliament-set-to-approve-EU-data-protection-law).
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: åŒæ ·ï¼Œæ•°æ®ä¿æŠ¤å¦‚ä»Šé€šå¸¸æ˜¯ä¸€ä¸ªé‡è¦è¯é¢˜ï¼Œç‰¹åˆ«æ˜¯è€ƒè™‘åˆ°æ¬§ç›Ÿçš„ã€Šé€šç”¨æ•°æ®ä¿æŠ¤æ¡ä¾‹ã€‹[Regulation](http://www.computerweekly.com/news/450281144/European-Parliament-set-to-approve-EU-data-protection-law)ã€‚
- en: Under theÂ Reliability Pillar, its worth calling out â€œTest recovery proceduresâ€.
    Â Unfortunately this test is all to often never attempted, leaving to chance the
    risk that when recovery is needed, its not going to work as expected ğŸ˜¦
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: åœ¨å¯é æ€§æ”¯æŸ±ä¸‹ï¼Œå€¼å¾—ä¸€æçš„æ˜¯â€œæµ‹è¯•æ¢å¤ç¨‹åºâ€ã€‚ ä¸å¹¸çš„æ˜¯ï¼Œè¿™ç§æµ‹è¯•ç»å¸¸è¢«å¿½è§†ï¼Œå¯¼è‡´æ¢å¤æ—¶å‡ºç°æ„å¤–æƒ…å†µçš„é£é™©ï¼Œè¿™ç§æƒ…å†µä¸ä¼šæŒ‰é¢„æœŸè¿›è¡Œ ğŸ˜¦
- en: ~ by mdavey on April 13, 2016.
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: ~ ç”± mdavey äº 2016 å¹´ 4 æœˆ 13 æ—¥å‘å¸ƒã€‚
- en: Posted in [Cloud](https://mdavey.wordpress.com/category/hpc/cloud/)
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: å‘å¸ƒåœ¨ [äº‘](https://mdavey.wordpress.com/category/hpc/cloud/) ä¸­
- en: 'Tags: [AWS](https://mdavey.wordpress.com/tag/aws/)'
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: æ ‡ç­¾ï¼š[AWS](https://mdavey.wordpress.com/tag/aws/)
