- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: æœªåˆ†ç±»'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 05:34:15'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Well-Architected Applications â€“ AWS Cloud and More | Tales from a Trading Desk
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: æ¥æºï¼š[https://mdavey.wordpress.com/2016/04/13/well-architected-applications-aws-cloud-and-more/#0001-01-01](https://mdavey.wordpress.com/2016/04/13/well-architected-applications-aws-cloud-and-more/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Well-Architected Applications â€“ AWS Cloud andÂ More
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Although â€œAWS [Well-Architected](https://d0.awsstatic.com/whitepapers/architecture/AWS_Well-Architected_Framework.pdf)
    Frameworkâ€ is clearly cloud focused, it has in my view a lot of relevant material
    for non-cloud applications. Â AWS Well-Architected Framework is based on four pillarsâ€”security,
    reliability, performance efficiency, and cost optimization. Â Clearly all four
    pillars are relevant to non-cloud applications, with cost optimization being high
    up due to budgets, hardware purchases, and data centre space.
  prefs: []
  type: TYPE_NORMAL
- en: Cloud does have a number of benefits, one of which is â€œLower the risk of architecture
    changeâ€ â€“ something that all of us have probably experienced, testing in an environment
    which has a considerable delta to production. Â Cloud offers â€œautomate the creation
    of test environments that emulate your production configurations, you can carry
    out testing easily.â€
  prefs: []
  type: TYPE_NORMAL
- en: Similarly, data protection these days is often an important topic, especially
    in light of the EUâ€™sÂ General Data Protection [Regulation](http://www.computerweekly.com/news/450281144/European-Parliament-set-to-approve-EU-data-protection-law).
  prefs: []
  type: TYPE_NORMAL
- en: Under theÂ Reliability Pillar, its worth calling out â€œTest recovery proceduresâ€.
    Â Unfortunately this test is all to often never attempted, leaving to chance the
    risk that when recovery is needed, its not going to work as expected ğŸ˜¦
  prefs: []
  type: TYPE_NORMAL
- en: ~ by mdavey on April 13, 2016.
  prefs: []
  type: TYPE_NORMAL
- en: Posted in [Cloud](https://mdavey.wordpress.com/category/hpc/cloud/)
  prefs: []
  type: TYPE_NORMAL
- en: 'Tags: [AWS](https://mdavey.wordpress.com/tag/aws/)'
  prefs: []
  type: TYPE_NORMAL
